###
GET http://127.0.0.1:8080

###
GET http://127.0.0.1:8080/customer
Accept: application/json

###
GET http://127.0.0.1:8080/customer/300
Accept: application/json

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json
{
  "id": "300",
  "firstName": "Mary",
  "lastName": "Smith",
  "email": "mary.smith@company.com"
}